Added support for ISO EDTT/HCI commands and ISO HCI events
EDTTool/EDTT pull request #27
Opened 2021-03-10 12:20 UTC by mtpr-ot

The following ISO HCI events have been added:
- BT_HCI_EVT_LE_CIS_ESTABLISHED
- BT_HCI_EVT_LE_CIS_REQUEST
 
The following ISO HCI commands have been added:
- le_set_cig_parameters
- le_set_cig_parameters_test
- le_create_cis
- le_remove_cig
- le_accept_cis_request
- le_reject_cis_request
- le_setup_iso_data_path
- le_remove_iso_data_path
- le_set_host_feature

The following ISO EDTT commands have been added:
- le_iso_data_flush
- le_iso_data_ready
- le_iso_data_write
- le_iso_data_read
    
    Signed-off-by: Morten Priess <mtpr@oticon.com>

2021-03-12 11:37 UTC, thoh-ot requested changes

2021-03-12 14:49 UTC, mtpr-ot commented on src/components/basic_commands.py
> +                      PhyMToS, PhySToM, BnMToS, BnSToM)
Ouch, didn't know that. Will try to find all the palces.

2021-03-12 14:54 UTC, mtpr-ot commented on src/components/events.py
> +            cigSyncDelay, cisSyncDelay = struct.unpack('<3B3B', self.data[4:10])
So should it be this instead:
```
cigSyncDelay = struct.unpack('<3B', self.data[4:7])
cisSyncDelay = struct.unpack('<3B', self.data[7:10])
```

2021-03-12 15:06 UTC, mtpr-ot commented on src/components/basic_commands.py
> +        raise Exception("LE Accept CIS Request command failed: Response length field corrupted (%i)" % RespLen)
So:
`if ( RespLen != 1 ):`?

2021-03-12 15:07 UTC, mtpr-ot commented on src/components/basic_commands.py
> +        raise Exception("LE Accept CIS Request command failed: Response length field corrupted (%i)" % RespLen)
So `return 0`?

2021-03-12 15:11 UTC, mtpr-ot commented on src/components/basic_commands.py
> +    packet = transport.recv(idx, 5, to)
Ok, hard miss.

2021-03-15 07:42 UTC, thoh-ot requested changes

2021-03-15 07:42 UTC, thoh-ot commented on src/components/basic_commands.py
> +    packet = transport.recv(idx, 4, to)
There is a 1 byte status parameter in the response packet, that needs to be received, unpacked and returned.

2021-03-15 07:42 UTC, thoh-ot commented on src/components/basic_commands.py
> +        raise Exception("LE Accept CIS Request command failed: Response length field corrupted (%i)" % RespLen)
There is a 1 byte status parameter in the response packet, that needs to be received, unpacked and returned.

2021-03-15 14:13 UTC, thoh-ot requested changes

2021-03-15 14:13 UTC, thoh-ot commented on src/components/basic_commands.py
> +    cmd = struct.pack('<HHHHB,
Missing string termination in struct.pack format

2021-03-15 14:13 UTC, thoh-ot commented on src/components/events.py
> +        return status, connectionHandle, toNumber(cigSyncDelay), toNumber(cisSyncDelay), toNumber(transportLatencyMToS), toNumber(transportLatencySToM),
Add a `\` to the end of the line to allow for line continuation on next line

2021-03-16 12:17 UTC, thoh-ot commented
The new commands are missing Command Complete Event decode printing format in Event.__cceFormats__

2021-03-19 07:48 UTC, closed without merging

2021-03-19 07:49 UTC, mtpr-ot commented
Creating new clean PR