Wait for reply to wait command
EDTTool/EDTT pull request #61
Opened 2022-11-24 09:00 UTC by Tronil

The EDTT bridge will now reply to wait commands; Read this reply before returning from transport.wait()

Signed-off-by: Troels Nilsson <trnn@demant.com>

2022-11-24 09:00 UTC, Tronil commented
Corresponding change in EDTT bridge: https://github.com/BabbleSim/ext_device_EDTT_bridge/pull/1

2022-11-24 09:16 UTC, wopu-ot approved these changes

2022-11-25 12:56 UTC, aescolar commented
@Tronil how come you needed this change?

2022-11-25 13:05 UTC, Tronil commented
The EDTT tests some times need to wait to examine packets getting sent; e.g. in one case we have to wait until at least 100 LL_DATA packets have been sent over a newly established connection before passing the test case. This isn't really possible right now - you can call transport.wait(), but then you have no idea what the simulation time actually is since it doesn't wait until the simulation catches up. What we need is for the EDTT bridge to signal back when the simulation time has caught up so we can block in the transport.wait() and have a known simulation time.

2022-11-25 13:52 UTC, aescolar commented
I guess you have rerun all tests and they all pass?
(the change will slow thing a little bit, but I hope that is not a problem in itself)

2022-11-25 13:57 UTC, Tronil commented
> I guess you have rerun all tests and they all pass? (the change will slow thing a little bit, but I hope that is not a problem in itself)

Yes the tests all still pass. I didn't notice a significant slowdown from this, but I haven't measured it so I can't give any specifics.

2022-11-28 11:44 UTC, aescolar requested changes
Overall the change is ok.
A couple of minor requests:
* Docs:
Could you add here a line for the wait behavior:
https://github.com/EDTTool/EDTT/blob/main/docs/EDTT_transport_bsim.md?plain=1#L64
Update this: 
https://github.com/EDTTool/EDTT/blob/main/docs/EDTT_transport_bsim.md?plain=1#L128
Saying that it sends back a dummy byte when the wait is finished.
* Could you note in both commits (this and the one in bridge) that the change is not backwards compatible and requires the corresponding commit from the other?

2022-11-28 11:44 UTC, aescolar commented on src/components/edttt_bsim.py
> +        self.read(1);
could you add a comment here that we read this dummy byte, as this is the way for the bridge to tell us the wait time has been reached?

2022-11-28 11:46 UTC, aescolar commented
With those changes this seems fine to merge

2022-11-28 12:56 UTC, aescolar approved these changes

2022-11-28 14:46 UTC, merged